### ISSUE TITLE
How to serialize drawee?

### ISSUE THREAD

**Issue by jinsen47** [Bilibili/drawee-text-view#1]
I read the code and found the `DraweeSpan.java` didnt implement parcelable?
How can I pass it thru intent?

**Comment by yrom** [comment]
Sorry for late. I'll take time to look at this.

**Comment by yrom** [comment]
The `ParcelableSpan` interface is frameworks-only. That means cannot write `DraweeSpan` to parcel automatically, but you can write and read manually.

**Comment by daixiansen** [comment]
你好,加载本地资源图片时,图片会很虚,请问是什么原因啊?求解

**Comment by daixiansen** [comment]
加载网络图片也是,会变得很大呢
