### ISSUE TITLE
Subsequent `setText` calls don't display images.

### ISSUE THREAD

**Issue by mrkcsc** [Bilibili/drawee-text-view#5]
Hello - I have found that after calling `setText` on the same `DraweeTextView` twice, images no longer get displayed.

This is observed in places where re-use happens like a `RecyclerView`.

An example that show this behavior:

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final TextView textView = (TextView) findViewById(R.id.text_view);

        textView.setText(getSampleText());

        new Handler().postDelayed(new Runnable() {
            public void run() {
                textView.setText(getSampleText());
            }
        }, 5000);
    }

    private SpannableStringBuilder getSampleText() {
        int start;
        SpannableStringBuilder builder = new SpannableStringBuilder();
        builder.append("2333333\n");
        start = builder.length();
        builder.append("[emotion:tv_cheers]");
        DraweeSpan span = new DraweeSpan.Builder("http://static.yo9.com/web/emotions/tv_cheers.png").build();
        builder.setSpan(span, start, builder.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
        builder.append("bilibili- ( ゜- ゜)つロ 乾杯~\n");

        return builder;
    }
```

The second `setText` will no longer show the image.

PS: This is a great library, thanks for making it available :)

**Comment by yrom** [comment]
I have not run into this problem in using RecyclerView, calling `setText()` in ViewHolder's `onBind()`

**Comment by mrkcsc** [comment]
The above code will reproduce the bug when run, I can setup a demo project to make it easier to test.  In this case I just added it to an empty android project in the default activity.

**Comment by yrom** [comment]
Thanks for your report. This bug has been fixed.
