### ISSUE TITLE
is there a way make it show the circle drawee view .

### ISSUE THREAD

**Issue by snowjade** [Bilibili/drawee-text-view#6]
is there a way make it show the circle drawee view ?
just like  "roundAsCircle" "roundedCornerRadius" .

**Comment by yrom** [comment]
Just rewrite method `DraweeSpan#createDrawable()` to support construct [RoundedBitmapDrawable](https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/RoundedBitmapDrawable.java) and [RoundedCornersDrawable](https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/RoundedCornersDrawable.java). 
May you can read the source of [GenericDraweeHierarchy](https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchy.java) to get help

**Comment by snowjade** [comment]
ok,thanks. @yrom
